### PR TITLE
Handle grouped incidence2 data and add input checks

### LINKED ISSUE #52: Grouping for <incidence2> objects
This issue is about how the `prepare_data()` for `<incidence2>` objects treats grouped objects.

The current behaviour is to error when grouped `<incidence2>` objects are passed, and to advise users to call `incidence2::regroup()` on the object before passing it.

Alternatives include respecting the grouping structure, but this could require taking on a data science repository such as {data.table} or {dplyr} + {tidyr}, although base-R only options could also be implemented.

> Can we open another issue for the incidence2 grouping discussion please to make sure this stays on our radar? I think it's an important point.

_Originally posted by @Bisaloo in https://github.com/epiverse-trace/datadelay/issues/39#issuecomment-1602460696_

### PR DESCRIPTION
**Pull request by pratikunterwegs**
This PR adds support for grouped `incidence2` data and fixes #52 thanks to code from @TimTaylor.

This PR also adds some input checking for data.frames passed to `cfr_x()` functions.

### CODE REVIEW

**Comment by pratikunterwegs** [comment]
@jamesmbaazam would you be able to take a quick look at this PR before I merge it?

**Comment by jamesmbaazam** [comment]
Sure. What's your deadline?

**Comment by pratikunterwegs** [comment]
If you spot issues after I've merged I can fix those in separate PRs too, so whatever schedule works for you over this week.

**Comment by pratikunterwegs** [comment]
Thanks, this should be fixed in https://github.com/epiverse-trace/cfr/pull/83/commits/4441b74a669abbfb51a506fdb4e7ecb9a35a09f9

**Pull request merged**
